return {
    title = 'Picasa Metadata',
    id = 'org.usefultoys.picasatolightroom.metadata',
    items = {
        { 'com.adobe.label', label = LOC "$$$/Metadata/OrigLabel=Standard Metadata" },
        'com.adobe.filename',
        'com.adobe.folder',
        'com.adobe.separator',
        { 'com.adobe.label', label = 'Picasa Metadata' },
        'picasacaption',
        'picasakeywords',
        { 'com.adobe.label', label = 'Basic' },
        'picasarotate',
        'picasaenhance',
        'picasaautolight',
        'orgusefultoyspicasatolightroom metadataautocolor',
        'picasablackWhite',
        { 'com.adobe.label', label = 'Advanced' },
        'picasatilt',
        'picasatiltangle',
        'picasatiltscale',
        'picasacrop',
        'picasacropleft',
        'picasacropright',
        'picasacroptop',
        'picasacropbottom',
    },
}